console.log(typeof undefined);  
console.log(typeof null);       
console.log(typeof true);      
console.log(typeof 42);
console.log(typeof 'Hello');    
console.log(typeof {});         
console.log(typeof []);        
console.log(typeof function(){});
console.log(typeof Symbol()); 